---
# .github/ISSUE_TEMPLATE/config.yml

blank_issues_enabled: false
contact_links:
  - name: Qzark Community Support
    url: https://github.com/JuanVilla424/qzark/discussions
    about: Please ask and answer questions here.
  - name: Qzark Security Reports
    url: https://juanvilla424.github.io/qzark/SECURITY
    about: Please report security vulnerabilities here.
